[features]
seeds = false
skip-lint = false
[programs.devnet]
solana_revenue_sharing = "Faw7JrUgvfqjezMFaWhhMC8fVTP41mfUAypeWPP4tGyJ"

[registry]
url = "https://api.devnet.solana.com/"

[provider]
cluster = "Devnet"
wallet = "/Users/shriharikulkarni/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
